#!/usr/bin/env bash
# LowRankProjector v1 Pre-training Script
# This script mirrors scripts/pretrain.sh but swaps in the low-rank projector.
# Edit MODEL_PATH, DATA_PATH, IMAGE_FOLDER, and OUTPUT_DIR before running.

set -euo pipefail

# User-configurable paths
MODEL_PATH="/path/to/llama-or-compatible-backbone"         # e.g., /data/ssd_storage/llama/
DATA_PATH="./coco_projections_v1.json"                     # generated by LLaVA-NeXT/scripts/convert_coco_to_llava.py
IMAGE_FOLDER="/path/to/coco2014/train2014"                 # e.g., /data/ssd_storage/coco2014/train2014
OUTPUT_DIR="./checkpoints/llava-v1-lowrank-coco"

# Hyperparameters
RANK=64
BATCH_SIZE=16
ACC_STEPS=1
EPOCHS=1
LR="2e-3"
MM_PROJECTOR_LR="2e-3"
PROMPT_VERSION="plain"  # keep plain for pretraining (no special image tokens)

mkdir -p "${OUTPUT_DIR}"

deepspeed llava/train/train_mem.py \
    --deepspeed ./scripts/zero2.json \
    --model_name_or_path "${MODEL_PATH}" \
    --version "${PROMPT_VERSION}" \
    --data_path "${DATA_PATH}" \
    --image_folder "${IMAGE_FOLDER}" \
    --vision_tower openai/clip-vit-large-patch14-336 \
    --tune_mm_mlp_adapter True \
    --mm_projector_type "low_rank" \
    --mm_low_rank_rank ${RANK} \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --bf16 True \
    --output_dir "${OUTPUT_DIR}" \
    --num_train_epochs ${EPOCHS} \
    --per_device_train_batch_size ${BATCH_SIZE} \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps ${ACC_STEPS} \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 24000 \
    --learning_rate ${LR} \
    --mm_projector_lr ${MM_PROJECTOR_LR} \
    --weight_decay 0.0 \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 16 \
    --lazy_preprocess True \
    --report_to wandb